SELECT 
    SHIP_MODE, 
    SEGMENT, 
    COUNTRY, 
    CITY,
    STATE, 
    POSTAL_CODE,
    REGION,
    CATEGORY,
    SUB_CATEGORY,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT 
FROM PROJECT_OMS.CONSULTAS.DATASET_SUPERSTORE
